name: Build Evolution X for rosemary

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig

      - name: Initialize repo
        run: |
          mkdir evolutionx
          cd evolutionx
          repo init -u https://github.com/Evolution-X/manifest -b vic --git-lfs
          mkdir -p .repo/local_manifests
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <manifest>
            <project name="Evolution-X-Devices/device_xiaomi_rosemary" path="device/xiaomi/rosemary" remote="github" revision="main"/>
            <project name="RedmiNote10S/android_vendor_xiaomi_rosemary" path="vendor/xiaomi/rosemary" remote="github" revision="main"/>
            <project name="RedmiNote10S/android_kernel_redmi_rosemary" path="kernel/xiaomi/rosemary" remote="github" revision="main"/>
          </manifest>' > .repo/local_manifests/roomservice.xml

      - name: Sync source
        run: |
          cd evolutionx
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

      - name: Build ROM
        run: |
          cd evolutionx
          source build/envsetup.sh
          lunch evolution_rosemary-userdebug
          m evolution
